### ISSUE TITLE
Error on remove Viewer

### ISSUE THREAD

**Issue by mani1232** [Tofaa2/EntityLib#15]
```
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.remove(ConcurrentHashMap.java:4629) ~[?:?]
	at MXDrawer-1.0-SNAPSHOT-all.jar/com.matixgames.libs.entitylib.wrapper.WrapperEntity.removeViewer(WrapperEntity.java:242) ~[MXDrawer-1.0-SNAPSHOT-all.jar:?]
	at MXDrawer-1.0-SNAPSHOT-all.jar/com.matixgames.libs.entitylib.wrapper.WrapperEntity.removeViewer(WrapperEntity.java:257) ~[MXDrawer-1.0-SNAPSHOT-all.jar:?]
	at MXDrawer-1.0-SNAPSHOT-all.jar/com.matixgames.packet.PacketListener.onUserDisconnect(PacketListener.kt:26) ~[MXDrawer-1.0-SNAPSHOT-all.jar:?]
```

**Comment by Tofaa2** [comment]
When do you create the entity

**Comment by mani1232** [comment]
> When do you create the entity

![image](https://github.com/user-attachments/assets/6391bc6d-4fda-44b4-99c7-df54256cdee0)

**Comment by mani1232** [comment]
And im dont see it
![image](https://github.com/user-attachments/assets/3f363277-94a6-4124-95a8-56025fb41c22)

**Comment by Tofaa2** [comment]
The error is the uuid supplied is null somehow? Also consider using removeViewerSilently when disconnecting

**Comment by mani1232** [comment]
> The error is the uuid supplied is null somehow? Also consider using removeViewerSilently when disconnecting

![image](https://github.com/user-attachments/assets/0beb4099-3a96-42ad-8ff6-5f430de3beb2)
ok but im dont see entities

**Comment by mani1232** [comment]
Any idea why the centiti aren't spawning?

**Comment by Tofaa2** [comment]
UserLogin isnt the event to add the viewer in as the player hasnt even spawned at that time.

**Comment by mani1232** [comment]
> UserLogin isnt the event to add the viewer in as the player hasnt even spawned at that time.

Ok I'll fix it later, but that's not the problem, when I spawn the entity I add online players
